# generator_data.py
# Contains rich data definitions for the 20 new tools of MY USEFUL TOOLS

TOOLS_DATA = [
    {
        "id": "loan-interest",
        "name": "Loan Interest Calculator",
        "icon": "💳",
        "desc": "Calculate total interest expense, reducing vs flat rate comparison, and interest-to-principal ratio in INR (₹) or USD ($).",
        "tags": ["Interest Cost", "Borrowing", "Loans"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Loan Interest Calculator - Total Interest & Cost of Borrowing | MY USEFUL TOOLS",
        "meta_desc": "Calculate the total interest cost, interest vs principal percentage, and loan payoff breakdown in INR (₹) or USD ($). Free and 100% browser-based.",
    },
    {
        "id": "loan-eligibility",
        "name": "Loan Eligibility Calculator",
        "icon": "🎯",
        "desc": "Estimate maximum eligible loan amount and permissible EMI based on net monthly salary and FOIR debt limits.",
        "tags": ["FOIR", "Affordability", "Home Loan"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Loan Eligibility Calculator - Maximum Home & Personal Loan Eligibility | MY USEFUL TOOLS",
        "meta_desc": "Check your maximum eligible home, car, or personal loan amount based on net monthly income and FOIR debt limits. Fast, free, and client-side.",
    },
    {
        "id": "loan-tenure",
        "name": "Loan Tenure Calculator",
        "icon": "⏳",
        "desc": "Determine exact months and years needed to pay off a loan balance based on your desired monthly installment budget.",
        "tags": ["Payoff Time", "Debt Free", "EMI Budget"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Loan Tenure Calculator - Loan Payoff Time & Months to Debt Freedom | MY USEFUL TOOLS",
        "meta_desc": "Calculate how many months or years it will take to pay off a loan based on your affordable monthly payment. Free online payoff calculator.",
    },
    {
        "id": "salary",
        "name": "Salary Calculator",
        "icon": "💵",
        "desc": "Calculate take-home in-hand monthly salary from Annual CTC or Gross Pay with EPF, Professional Tax, and deductions.",
        "tags": ["Take-Home", "In-Hand Pay", "CTC Breakdown"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Salary Calculator - In-Hand Take-Home Pay & CTC Breakdown | MY USEFUL TOOLS",
        "meta_desc": "Calculate take-home in-hand monthly salary from Annual CTC or Gross Salary with PF, Professional Tax, and deductions in INR (₹).",
    },
    {
        "id": "overtime",
        "name": "Overtime Pay Calculator",
        "icon": "⏱️",
        "desc": "Calculate overtime wages with 1.5x time-and-a-half, 2.0x double time, and total blended gross paycheck across shifts.",
        "tags": ["Overtime", "1.5x Pay", "Wages"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Overtime Pay Calculator - Time-and-a-Half & Double Time Wages | MY USEFUL TOOLS",
        "meta_desc": "Calculate overtime earnings, 1.5x time-and-a-half, double time (2.0x), and total gross paycheck. Instant browser calculation.",
    },
    {
        "id": "tax",
        "name": "Tax Calculator",
        "icon": "📜",
        "desc": "Compare Indian Income Tax liability under the New Tax Regime vs Old Tax Regime with standard deduction & cess.",
        "tags": ["Income Tax", "New vs Old", "Tax Slabs"],
        "category": "Loans & Finance",
        "has_disclaimer": False,
        "page_title": "Tax Calculator - Income Tax Liability & New vs Old Regime | MY USEFUL TOOLS",
        "meta_desc": "Compute Indian Income Tax liability under the New Tax Regime vs Old Tax Regime with standard deduction, Section 87A rebate, and 4% cess.",
    },
    {
        "id": "calorie",
        "name": "Calorie Calculator",
        "icon": "🥗",
        "desc": "Determine daily calorie requirements for fat loss, maintenance, or muscle gain with macro breakdowns.",
        "tags": ["Nutrition", "Weight Loss", "Macros"],
        "category": "Health & Fitness",
        "has_disclaimer": True,
        "page_title": "Calorie Calculator - Daily Caloric Needs for Weight Loss & Gain | MY USEFUL TOOLS",
        "meta_desc": "Calculate daily caloric intake for weight loss, maintenance, or muscle gain with macro breakdowns using Mifflin-St Jeor formula.",
    },
    {
        "id": "bmr",
        "name": "BMR Calculator",
        "icon": "🔥",
        "desc": "Calculate Basal Metabolic Rate—the exact daily calorie expenditure burned by vital organs at complete physical rest.",
        "tags": ["Metabolism", "Resting Burn", "Mifflin-St Jeor"],
        "category": "Health & Fitness",
        "has_disclaimer": True,
        "page_title": "BMR Calculator - Basal Metabolic Rate & Resting Calorie Burn | MY USEFUL TOOLS",
        "meta_desc": "Calculate Basal Metabolic Rate (BMR)—the exact calories burned at rest by your vital organs with Mifflin-St Jeor and Harris-Benedict formulas.",
    },
    {
        "id": "tdee",
        "name": "TDEE Calculator",
        "icon": "⚡",
        "desc": "Calculate Total Daily Energy Expenditure factoring in basal metabolism, physical activity levels, and daily exercise energy burn.",
        "tags": ["Energy Burn", "TDEE", "Fitness"],
        "category": "Health & Fitness",
        "has_disclaimer": True,
        "page_title": "TDEE Calculator - Total Daily Energy Expenditure & Calorie Burn | MY USEFUL TOOLS",
        "meta_desc": "Calculate Total Daily Energy Expenditure (TDEE) factoring in metabolic rate and exercise intensity for cutting, maintenance, or bulking.",
    },
    {
        "id": "pregnancy-due-date",
        "name": "Pregnancy Due Date Calculator",
        "icon": "👶",
        "desc": "Estimate your baby's due date, gestational age in weeks & days, trimester, and pregnancy milestone calendar.",
        "tags": ["Due Date", "Trimesters", "Pregnancy"],
        "category": "Health & Fitness",
        "has_disclaimer": True,
        "page_title": "Pregnancy Due Date Calculator - EDD, Gestational Age & Trimesters | MY USEFUL TOOLS",
        "meta_desc": "Estimate your baby's due date, gestational age in weeks & days, trimester, and pregnancy milestones using Naegele's rule.",
    },
    {
        "id": "hours-to-minutes",
        "name": "Hours to Minutes Converter",
        "icon": "⏲️",
        "desc": "Convert decimal hours or combined hours and minutes into total minutes, seconds, milliseconds, and decimal workday ratios.",
        "tags": ["Hours to Mins", "Time Conversion", "Payroll"],
        "category": "Everyday & Conversion",
        "has_disclaimer": False,
        "page_title": "Hours to Minutes Converter - Decimal Hours to Total Minutes | MY USEFUL TOOLS",
        "meta_desc": "Convert decimal hours or hours + minutes into exact total minutes, seconds, and workday proportions with instant lookup tables.",
    },
    {
        "id": "minutes-to-hours",
        "name": "Minutes to Hours Converter",
        "icon": "🕰️",
        "desc": "Convert elapsed minutes into decimal hours, clock time (HH:MM), and workday progress percentages with quick lookup tables.",
        "tags": ["Mins to Hours", "Timesheets", "Decimal Hours"],
        "category": "Everyday & Conversion",
        "has_disclaimer": False,
        "page_title": "Minutes to Hours Converter - Minutes to Decimal Hours & Time | MY USEFUL TOOLS",
        "meta_desc": "Convert total minutes into decimal hours, hours & minutes, seconds, and work shifts. Ideal for payroll and billing timesheets.",
    },
    {
        "id": "length-converter",
        "name": "Length Converter",
        "icon": "📏",
        "desc": "Convert distances across millimeters, centimeters, meters, kilometers, inches, feet, yards, miles, and nautical miles.",
        "tags": ["Metric / Imperial", "Meters to Feet", "Distance"],
        "category": "Unit Converters",
        "has_disclaimer": False,
        "page_title": "Length Converter - Convert Meters, Feet, Inches, Miles & KM | MY USEFUL TOOLS",
        "meta_desc": "Convert length and distance between millimeters, centimeters, meters, kilometers, inches, feet, yards, and miles instantly.",
    },
    {
        "id": "weight-converter",
        "name": "Weight Converter",
        "icon": "⚖️",
        "desc": "Convert mass between milligrams, grams, kilograms, metric tonnes, ounces, pounds, stones, and Indian quintals.",
        "tags": ["Kg to Lbs", "Grams", "Mass"],
        "category": "Unit Converters",
        "has_disclaimer": False,
        "page_title": "Weight Converter - Convert Kilograms, Pounds, Grams & Ounces | MY USEFUL TOOLS",
        "meta_desc": "Convert weight and mass across milligrams, grams, kilograms, metric tonnes, ounces, pounds, and stones. Free and browser-based.",
    },
    {
        "id": "temperature-converter",
        "name": "Temperature Converter",
        "icon": "🌡️",
        "desc": "Convert temperatures between Celsius (°C), Fahrenheit (°F), and Kelvin (K) with step-by-step formulas and benchmark bars.",
        "tags": ["Celsius to Fahrenheit", "Kelvin", "Thermal Scales"],
        "category": "Unit Converters",
        "has_disclaimer": False,
        "page_title": "Temperature Converter - Celsius, Fahrenheit & Kelvin Conversion | MY USEFUL TOOLS",
        "meta_desc": "Convert temperatures accurately between Celsius (°C), Fahrenheit (°F), and Kelvin (K) with step-by-step math and thermal markers.",
    },
    {
        "id": "area-converter",
        "name": "Area Converter",
        "icon": "🗺️",
        "desc": "Convert land and construction areas across square feet, square meters, acres, hectares, guntha, bigha, and square yards.",
        "tags": ["Square Feet", "Acres", "Land Units"],
        "category": "Unit Converters",
        "has_disclaimer": False,
        "page_title": "Area Converter - Convert Square Feet, Meters, Acres & Hectares | MY USEFUL TOOLS",
        "meta_desc": "Convert land and geometric area between square meters, square feet, acres, hectares, guntha, bigha, and square yards.",
    },
    {
        "id": "volume-converter",
        "name": "Volume Converter",
        "icon": "🧪",
        "desc": "Convert liquids and volume across milliliters, liters, cubic meters, US gallons, fluid ounces, pints, cups, and cubic feet.",
        "tags": ["Liters to Gallons", "Cooking Units", "Capacity"],
        "category": "Unit Converters",
        "has_disclaimer": False,
        "page_title": "Volume Converter - Convert Liters, Gallons, Milliliters & Cups | MY USEFUL TOOLS",
        "meta_desc": "Convert liquid volume and capacity between milliliters, liters, cubic meters, gallons, cups, fluid ounces, and cubic feet.",
    },
    {
        "id": "tip",
        "name": "Tip Calculator",
        "icon": "🍽️",
        "desc": "Calculate restaurant tips, service gratuities, custom percentage additions, and fair bill splits per person in INR (₹) or USD ($).",
        "tags": ["Dining", "Gratuity", "Bill Split"],
        "category": "Everyday & Shopping",
        "has_disclaimer": False,
        "page_title": "Tip Calculator - Restaurant Gratuity & Bill Split Per Person | MY USEFUL TOOLS",
        "meta_desc": "Calculate restaurant tips, service gratuity, bill splitting per person, and custom tip percentages in INR (₹) or USD ($).",
    },
    {
        "id": "discount-final-price",
        "name": "Discount + Final Price Calculator",
        "icon": "🛍️",
        "desc": "Compute double / stacked promotional discounts (e.g., 30% off + extra 10% coupon) with optional sales tax and net savings.",
        "tags": ["Stacked Discounts", "Double Sale", "Shopping"],
        "category": "Everyday & Shopping",
        "has_disclaimer": False,
        "page_title": "Discount + Final Price Calculator - Stacked Discounts & Sale Price | MY USEFUL TOOLS",
        "meta_desc": "Compute stacked discounts (double discounts e.g. 40% + extra 15% off) plus optional sales tax / GST and net customer savings.",
    },
    {
        "id": "sales-tax",
        "name": "Sales Tax Calculator",
        "icon": "🏷️",
        "desc": "Add sales tax to pre-tax amounts or reverse-calculate pre-tax list price and tax amounts from tax-inclusive retail totals.",
        "tags": ["Sales Tax", "Tax Inclusive", "Tax Exclusive"],
        "category": "Everyday & Shopping",
        "has_disclaimer": False,
        "page_title": "Sales Tax Calculator - Add or Reverse Sales Tax on Any Price | MY USEFUL TOOLS",
        "meta_desc": "Calculate sales tax addition (exclusive tax) or reverse-calculate pre-tax price from tax-inclusive retail total. Fast and free.",
    }
]
